// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW8fdealWNAR99VsNTzGJxGP5az2z7Gzw',
    appId: '1:518250795313:web:e2d28f6fbf5e8df222a010',
    messagingSenderId: '518250795313',
    projectId: 'ast-nearby-hospital-finder',
    authDomain: 'ast-nearby-hospital-find-94cd4.firebaseapp.com',
    storageBucket: 'ast-nearby-hospital-finder.appspot.com',
    measurementId: 'G-XV0YMD6L2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb0lO8BseFmjjjujdfW6b5uTO0r0eVQE4',
    appId: '1:518250795313:android:22824b1653795afb22a010',
    messagingSenderId: '518250795313',
    projectId: 'ast-nearby-hospital-finder',
    storageBucket: 'ast-nearby-hospital-finder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgYSZEgK2m7N4vxd691RxyA1C7KEJDjNg',
    appId: '1:518250795313:ios:e53fa92756c4559622a010',
    messagingSenderId: '518250795313',
    projectId: 'ast-nearby-hospital-finder',
    storageBucket: 'ast-nearby-hospital-finder.appspot.com',
    androidClientId: '518250795313-p0pqq49ikclqbosau9beaki4nkjfai4j.apps.googleusercontent.com',
    iosClientId: '518250795313-e3mqbo8dqigdne7psm42m8tddvg62ebq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbyHospitalLocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgYSZEgK2m7N4vxd691RxyA1C7KEJDjNg',
    appId: '1:518250795313:ios:7ad2607b0ff8373022a010',
    messagingSenderId: '518250795313',
    projectId: 'ast-nearby-hospital-finder',
    storageBucket: 'ast-nearby-hospital-finder.appspot.com',
    androidClientId: '518250795313-p0pqq49ikclqbosau9beaki4nkjfai4j.apps.googleusercontent.com',
    iosClientId: '518250795313-pn2opah9th56g66vp6c6oi8pmfsd1rsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearbyHospitalLocator.RunnerTests',
  );
}
